---
- name: IPython controller Playbook (standard user operations)
  hosts: ipython_controller:ipython_engine
  sudo: False

  tasks:

    - name: create ipython profile
      action: shell ipython profile create --parallel --profile-dir=/home/.ipython/profile_default
      tags:
        - ipython

    - name: Deploy ipcluster configuration file
      action: template src=ipython/templates/ipcluster_config.py.j2 dest=/home/.ipython/profile_default/ipcluster_config.py
      tags: 
        - ipython

    - name: Deploy ipcontroller configuration file
      action: template src=ipython/templates/ipcontroller_config.py.j2 dest=/home/.ipython/profile_default/ipcontroller_config.py
      tags: 
        - ipython

- name: IPython Notebook
  hosts: ipython_controller
  tasks:
    - name: add password to default profile
      lineinfile: dest=/home/.ipython/profile_default/ipython_notebook_config.py regexp="^# c.NotebookApp.password" line="c.NotebookApp.password = 'sha1:7866a895a798:3354ca0fa7421a3e537276ee2702a0dce5e9e3b7'"    

    - name: add SSH key
      copy: src=/home/kban/kban.priv dest=/root/kban.priv owner=root group=root mode=400

    - name: start notebook
      action: shell export IPYTHONDIR=/home/.ipython ; nohup ipython notebook --notebook-dir=/data > /dev/null 2>&1 &
      tags:
        - ipython

  handlers:
    - include: common/handlers/main.yml
