---
- name: Restart Infiniband interface
  hosts: all
  tasks:
    - shell: ifdown ib0 && ifup ib0

- include: roles/common.yml
- include: roles/ganglia.yml
- include: roles/gridengine.yml
- include: roles/hadoop.yml
- include: roles/pvfs2.yml
- include: roles/ceph.yml
- include: roles/gluster.yml
- include: roles/ipython.yml
- include: roles/ngrok.yml
- include: roles/ansible.yml
- include: roles/final.yml
